"""add universities and campuses tables

Revision ID: 611aeb3645e3
Revises: b6767b4eae6c
Create Date: 2026-09-08 14:32:36.843851

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '611aeb3645e3'
down_revision: str | Sequence[str] | None = 'b6767b4eae6c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
