"""add universities and campuses tables

Revision ID: 91857cb3d5d7
Revises: 611aeb3645e3
Create Date: 2026-09-08 14:46:30.705087

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '91857cb3d5d7'
down_revision: str | Sequence[str] | None = '611aeb3645e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'universities',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('official_name', sa.String(), nullable=False),
        sa.Column('normalized_name', sa.String(), nullable=False),
        sa.Column('short_name', sa.String(), nullable=True),
        sa.Column('institution_type', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='ACTIVE'),
        sa.Column('country', sa.String(), nullable=False, server_default='Nigeria'),
        sa.Column('state_region', sa.String(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.CheckConstraint("institution_type IN ('UNIVERSITY', 'COLLEGE', 'POLYTECHNIC', 'MONOTECHNIC')"),
        sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_normalized_name'), 'universities', ['normalized_name'], unique=True)

    op.create_table(
        'campuses',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('university_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('normalized_name', sa.String(), nullable=False),
        sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column('city', sa.String(), nullable=True),
        sa.Column('state_region', sa.String(), nullable=True),
        sa.Column('is_main_campus', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('status', sa.String(), nullable=False, server_default='ACTIVE'),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')"),
        sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('university_id', 'normalized_name', name='idx_campus_university_normalized_name')
    )
    op.create_index(
        'idx_campus_main_per_university',
        'campuses',
        ['university_id'],
        unique=True,
        postgresql_where=sa.text('is_main_campus = true')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_campus_main_per_university', table_name='campuses')
    op.drop_table('campuses')
    op.drop_index(op.f('ix_universities_normalized_name'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
