"""add profile tables

Revision ID: d5dc185458b0
Revises: c022ee5677c4
Create Date: 2026-09-01 17:35:48.029466

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd5dc185458b0'
down_revision: str | Sequence[str] | None = 'c022ee5677c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('profile_type', sa.Enum('STUDENT', 'SCOUT', name='profiletype'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id')
    )
    op.create_table('scout_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('business_description', sa.String(), nullable=True),
    sa.Column('years_active', sa.Integer(), nullable=True),
    sa.Column('availability_status', sa.Enum('ACTIVE', 'PAUSED', name='scoutavailabilitystatus'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('student_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('university_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('budget_min_naira', sa.Integer(), nullable=True),
    sa.Column('budget_max_naira', sa.Integer(), nullable=True),
    sa.Column('preferred_accommodation_type', sa.Enum('SELF_CONTAINED', 'SHARED_ROOM', 'HOSTEL', 'NO_PREFERENCE', name='accommodationtypepreference'), nullable=True),
    sa.Column('cleanliness_preference', sa.Enum('VERY_TIDY', 'MODERATE', 'RELAXED', name='cleanlinesspreference'), nullable=True),
    sa.Column('sleep_schedule', sa.Enum('EARLY_BIRD', 'NIGHT_OWL', 'FLEXIBLE', name='sleepschedule'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    op.drop_table('scout_profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
